create table softwares(
    id number generated by default as identity,
    serial varchar2(15),
    fabricante varchar2(30),
    nome varchar2(30),
    categoria varchar2(20),
    preco number,
    primary key(id)
);

insert into softwares (serial, fabricante, nome, categoria, preco) values('KJHS89763IA6J39','Steam', 'FEED AND GROW FISH', 'GAME', 26.98);
insert into softwares (serial, fabricante, nome, categoria, preco) values('ALKJAD8938998SS','Google', 'Angular', 'Framework', 126.3);
insert into softwares (serial, fabricante, nome, categoria, preco) values('985KHDKJFK98474','Facebook', 'React', 'Framework', 1325.25);